### ISSUE TITLE
Vulnerabilities found by SonarQube

### ISSUE THREAD

**Issue by pappbence96** [BME-MIT-IET/Git-egylet-iet-2019#2]
SonarQube found the following vulnerabilities:
-1 critical
-3 blocker
-51 minor

**Comment by pappbence96** [comment]
Related commits:
04bfd9f 
3a1a6e8
881021f

**Comment by pappbence96** [comment]
Additional fix:
17b6af4c5c6489c22ecbcc5e0f620cba8f0fa738

**Comment by koppa96** [comment]
For some reason the issue was not closed automatically by the merge of the referencing pull request, so I close it manually. The issue was closed with #5.
