### ISSUE TITLE
App crashes with SAXNotRecognizedException on startup

### ISSUE THREAD

**Issue by archetiz** [BME-MIT-IET/Git-egylet-iet-2019#25]
After a fresh install the app crashes with SAXNotRecognizedException on startup.

Relevant line: [MigrationHelper.java#237](https://github.com/BME-MIT-IET/Git-egylet-iet-2019/blob/d6aaf8441ae103ea5eee89c7e926f08e020290b3/app/src/main/java/org/gnucash/android/db/MigrationHelper.java#L237)

**Comment by koppa96** [comment]
Fixed in d920a37bab60529b6a9ecad0c81e3016839151fd
Seems like the implementation that is used does not support that setting.

**Comment by archetiz** [comment]
Yeah, the issue appears to be within SAXParser itself. Details: https://stackoverflow.com/a/24148858
